class Codes {
  static const List<String> numbers = [
    '00', '01', '02', '03', '04', '05', '06', '07', '08', '09',
    '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
    '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
    '30', '31', '32', '33', '34', '35', '36', '37', '38', '39',
    '40', '41', '42', '43', '44', '45', '46', '47', '48', '49',
    '50', '51', '52', '53', '54', '55', '56', '57', '58', '59',
    '60', '61', '62', '63', '64', '65', '66', '67', '68', '69',
    '70', '71', '72', '73', '74', '75', '76', '77', '78', '79',
    '80', '81', '82', '83', '84', '85', '86', '87', '88', '89',
    '90', '91', '92', '93', '94', '95', '96', '97', '98', '99',
  ];

  static const Map<String, List<String>> numbersCodes = {
    'en': [
      'RoveR',
      'paper RoLL',
      'RaBBit',
      'RoCket',
      'RoD',
      'RiFle',
      'RaPtor (dinosaur)',
      'eRaSer',
      'RuG',
      'iRoN',
      'LemuR',
      'LiLy',
      'LoBster',
      'LoCK',
      'LiD',
      'LeaF',
      'eLePhant',
      'iLLeSt (wheelchair)',
      'LuGGage',
      'LioN',
      'BeaR',
      'BaLL',
      'BuBBle gum',
      'BuCKet',
      'BeD',
      'ButterFly',
      'BumPer',
      'BuS',
      'BuG',
      'BaNana',
      'CRocodile',
      'CameL',
      'rubik\'s CuBe',
      'CaCtus',
      'CoD',
      'CaViar',
      'CaP',
      'ChainSaw',
      'CiGar',
      'KaNgaroo',
      'DRagon',
      'DoLL',
      'DuBai tower',
      'DuCK',
      'DoDge challenger',
      'DeFence (armor)',
      'DolPhin',
      'DiSk',
      'DouGh',
      'DoNkey',
      'FRog',
      'FLy',
      'FaBric',
      'FoX',
      'WooD',
      'Wi-Fi (router)',
      'WolF',
      'FiShing rod',
      'FiG',
      'FaN',
      'PaRRot',
      'PLate',
      'PitBull',
      'PeaCock',
      'PeDal',
      'PitchFork',
      'PorcuPine',
      'PiStol',
      'PenGuin',
      'PeN',
      'ShaRk',
      'SeaL',
      'SkateBoard',
      'SoCKs',
      'SworD',
      'SurFer',
      'SPider',
      'SauSages',
      'SeaGull',
      'SNake',
      'GoRilla',
      'GLobe',
      'GoBlin',
      'GreeK',
      'GoDzilla',
      'GiraFFe',
      'JeeP',
      'GooSe',
      'GaGarin (austronaut)',
      'GuN',
      'NaRcotics (syringe)',
      'NaiL',
      'NiB',
      'taNK',
      'NoDe',
      'kNiFe',
      'iNPut (door)',
      'NASA (fighter jet)',
      'NuGGets',
      'NiNja',
    ],
    'ru': [
      'аНаНас',
      'НоКиа',
      'НЛо',
      'НиТки',
      'НоЧник',
      'НаПерсток',
      'НоЖ',
      'НоСок',
      'НеВеста',
      'НарДы',
      'КНига',
      'Кактус',
      'КоЛокол',
      'КоТ',
      'КаЧели',
      'КеПка',
      'КоШелёк',
      'КоСа',
      'КороВа',
      'КеДы',
      'ЛимоН',
      'ЛуК',
      'ЛиЛия',
      'ЛаТы',
      'ЛиЧинка',
      'ЛоПата',
      'ЛоШадь',
      'ЛиСа',
      'ЛеВ',
      'ЛоДка',
      'ТаНк',
      'уТКа',
      'ТюЛень',
      'ТорТ',
      'ТоЧилка',
      'ТоПор',
      'ТуШканчик',
      'ТеСто',
      'ТВ (телевизор)',
      'ТеДди (мишка)',
      'ЧайНик',
      'ЧайКа',
      'ЧиЛи (перец)',
      'Чёрт',
      'ЧуЧело',
      'ЧереП',
      'ЧаШка',
      'ЧаСы',
      'ЧерВь',
      'ЧемоДан',
      'ПеНь',
      'ПауК',
      'ПиЛа',
      'ПеТух',
      'Печь',
      'ПоПугай',
      'ПуШка',
      'ПиСтолет',
      'ПаВлин',
      'ПеДаль',
      'ШиНа',
      'ШоКолад',
      'ШиЛо',
      'ШорТы',
      'Шахматы',
      'ШПага',
      'ШиШка',
      'ШеСт',
      'ШВабра',
      'ШеДевр (статуя)',
      'СаНи',
      'СоК',
      'СЛон',
      'СиТо',
      'СаЧок',
      'СаПог',
      'СуШи',
      'СоСиски',
      'СоВа',
      'СаДовник',
      'ВиНо',
      'ВаКцина',
      'ВиЛы',
      'ВеТка',
      'ВраЧ',
      'ВамПир',
      'ВиШня',
      'ВеСы',
      'ВерёВка',
      'ВеДро',
      'ДыНя',
      'ДиКообраз',
      'ДеЛьфин',
      'ДяТел',
      'УДоЧка',
      'ДуПло',
      'ДуШ',
      'ДоСка',
      'ДВерь',
      'ДуДочка',
    ]
  };

  static const List<String> characteristics = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',];

  static const Map<String, List<String>> characteristicsCodes = {
    'en': [
      'Toy, dummy, clown',
      'Battered by life',
      'Christmas',
      'Medical',
      'Glamorous',
      'Ancient',
      'Woolly, hairy, curly',
      'Metal',
      'Military',
      'Futuristic',
    ],
    'ru': [
      'Игрушечный, муляжный',
      'Потрёпанный жизнью',
      'Новогодний',
      'Медицинский',
      'Гламурный',
      'Древний',
      'Шерстяной, волосатый, кудрявый',
      'Металлический',
      'Военный',
      'Футуристический',
    ]
  };


  static const Map<String, List<String>> months = {
    'en': [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    'ru': [
      'Январь',
      'Февраль',
      'Март',
      'Апрель',
      'Май',
      'Июнь',
      'Июль',
      'Август',
      'Сентябрь',
      'Октябрь',
      'Ноябрь',
      'Декабрь',
    ]
  };

  static const Map<String, List<String>> monthsCodes = {
    'ru': [
      'Ёлка',
      'Фен',
      'Мачта',
      'Клоун',
      'Голубь',
      'Клубника',
      'Юла',
      'Пляжный мяч',
      'Ручка',
      'Осьминог',
      'Снеговик',
      'Бакал с шампанским',
    ],
    'en': [
      'Christmas tree',
      'Fan',
      'Mast',
      'Clown',
      'Pigeon',
      'Strawberry',
      'Yula',
      'Beach Ball',
      'Pen',
      'Octopus',
      'Snowman',
      'A glass of champagne',
    ]
  };

  static const List<String> rusAlphabet = [
    'А','Б','В','Г', 'Д',
    'Е','Ё', 'Ж', 'З',
    'И','Й', 'К','Л', 'М',
    'Н','О','П', 'Р',
    'С','Т','У', 'Ф',
    'Х','Ц','Ч', 'Ш',
    'Щ', 'Э','Ю','Я'
  ];

  static const List<String> rusAlphabetCodes = [
    'Арка',
    'Бур',
    'Винтовка',
    'Грабли',
    'Динозавр',
    'Енот',
    'Ёршик',
    'Журавль',
    'Зуб',
    'Индюк',
    'Йо-Йо',
    'Карась',
    'Лось',
    'Миниган',
    'Ножницы',
    'Обруч',
    'Пакет',
    'Рак',
    'Сетка',
    'Тигр',
    'Уж',
    'Футбольный мяч',
    'Хоккейная клюшка',
    'Цербер',
    'Чушка (свинья)',
    'Шакал',
    'Щука',
    'Эльф',
    'Юбка',
    'Яхта',
  ];



  static const List<String> enAlphabet = [
    'A','B','C','D',
    'E','F','G','H',
    'I','J','K', 'L', 'M', 'N', 'O',
    'P','Q','R','S',
    'T','U','V','W',
    'X','Y','Z',
  ];

  static const List<String> enSmallAlphabet = [
    'a','b','c','d',
    'e','f','g','h',
    'i','j','k', 'l', 'm', 'n', 'o',
    'p','q','r','s',
    't','u','v','w',
    'x','y','z',
  ];


  static const Map<String, List<String>> enAlphabetCodes = {
    'en': [
      'Ant',
      'Barrel',
      'Cat',
      'Deer',
      'Egg',
      'Fork',
      'Golf stick',
      'Helicopter',
      'Ice cream',
      'Jellyfish',
      'Kettle',
      'Lizard',
      'Mouse',
      'Notebook',
      'Ox',
      'Poodle',
      'Quill',
      'Robot',
      'Snail',
      'Turtle',
      'Umbrella',
      'Vacuum cleaner',
      'Wings',
      'Rocket (space X)',
      'Yak',
      'Zombie',
    ],
    'ru': [
      'Ant',
      'Bear',
      'Camel',
      'Dolphin',
      'Egg',
      'Fork',
      'Gorilla',
      'Helicopter',
      'Ice cream',
      'Jellyfish',
      'Kangaroo',
      'Lizard',
      'Mouse',
      'Notebook',
      'Ox',
      'Poodle',
      'Quill',
      'Rabbit',
      'Snail',
      'Turtle',
      'Umbrella',
      'Vacuum cleaner',
      'Wolf',
      'Rocket (space X)',
      'Yak',
      'Zombie',
    ]
  };

  static const List<String> specialSymbols = [
    '~','!','@','"','#','№','\$',';','%','^',':','&','?', '*', '(', ')', '_', '-', '+', '=', '/', '|', '\\', ',','.','<','>'
  ];

  static const Map<String, List<String>> specialSymbolsCodes = {
    'en': [
      'Wig with curly hair',
      'Road danger sign',
      'Dog',
      'Curtain',
      'Sewer grate',
      'Car number',
      'A bundle of money',
      'Baited Hook',
      'A piece of pie or pizza',
      'Hat',
      'Socket',
      'Glasses',
      'Incandescent lamp',
      'Star',
      'Shield',
      'Sled',
      'Hatch',
      'Stick',
      'Ambulance',
      'Socket plug',
      'Stepladder',
      'Wall',
      'Ladder',
      'Hook',
      'Golf Ball',
      'Cone',
      'Arrow',
    ],
    'ru': [
      'Парик с кудрявыми волосами',
      'Дорожный знак опасности',
      'Собака',
      'Штора',
      'Решётка канализации',
      'Номер машины',
      'Пачка денег',
      'Крючок с наживкой',
      'Кусок пирога или пиццы',
      'Шапка',
      'Розетка',
      'Очки',
      'Лампа накаливания',
      'Звезда',
      'Щит',
      'Ледянка',
      'Люк',
      'Палка',
      'Машина скорой помощи',
      'Вилка для розетки',
      'Стремянка',
      'Стена',
      'Лестница',
      'Крюк',
      'Шарик для гольфа',
      'Конус',
      'Стрела',
    ]
  };

  static const Map<String, List<String>> namesMale = {
    'en': [
      'Aaron',
      'Adam',
      'Adrian',
      'Aidan',
      'Alex',
      'Alexander',
      'Andrew',
      'Anthony',
      'Antonio',
      'Ashton',
      'Austin',
      'Benjamin',
      'Blake',
      'Brandon',
      'Brian',
      'Bryan',
      'Caleb',
      'Cameron',
      'Carlos',
      'Carter',
      'Charles',
      'Chase',
      'Christian',
      'Christopher',
      'Cody',
      'Cole',
      'Colin',
      'Connor',
      'Daniel',
      'David',
      'Devin',
      'Diego',
      'Dominic',
      'Dylan',
      'Elijah',
      'Eric',
      'Ethan',
      'Evan',
      'Gabriel',
      'Gavin',
      'Hayden',
      'Hunter',
      'Ian',
      'Isaac',
      'Isaiah',
      'Jack',
      'Jackson',
      'Jacob',
      'Jaden',
      'James',
      'Jason',
      'Jayden',
      'Jeremiah',
      'Jesse',
      'Jesus',
      'John',
      'Jonathan',
      'Jordan',
      'Jose',
      'Joseph',
      'Joshua',
      'Juan',
      'Julian',
      'Justin',
      'Kevin',
      'Kyle',
      'Landon',
      'Logan',
      'Lucas',
      'Luis',
      'Luke',
      'Mason',
      'Matthew',
      'Michael',
      'Miguel',
      'Nathan',
      'Nathaniel',
      'Nicholas',
      'Noah',
      'Owen',
      'Patrick',
      'Richard',
      'Robert',
      'Ryan',
      'Samuel',
      'Sean',
      'Sebastian',
      'Steven',
      'Thomas',
      'Timothy',
      'Tyler',
      'William',
      'Wyatt',
      'Xavier',
      'Zachary',
    ],
    'ru': [
      'Александр',
      'Алексей',
      'Альберт',
      'Анатолий',
      'Андрей',
      'Антон',
      'Аркадий',
      'Арсений',
      'Артём',
      'Артур',
      'Афанасий',
      'Борис',
      'Вадим',
      'Валентин',
      'Валерий',
      'Василий',
      'Виктор',
      'Виталий',
      'Владимир',
      'Владислав',
      'Всеволод',
      'Вячеслав',
      'Геннадий',
      'Георгий',
      'Глеб',
      'Григорий',
      'Даниил',
      'Денис',
      'Дмитрий',
      'Евгений',
      'Егор',
      'Захар',
      'Иван',
      'Игорь',
      'Илья',
      'Кирилл',
      'Константин',
      'Лев',
      'Леонид',
      'Макар',
      'Максим',
      'Марк',
      'Матвей',
      'Михаил',
      'Никита',
      'Николай',
      'Олег',
      'Остап',
      'Павел',
      'Пётр',
      'Ренат',
      'Роман',
      'Ростислав',
      'Руслан',
      'Рустам',
      'Святослав',
      'Семён',
      'Сергей',
      'Станислав',
      'Степан',
      'Тарас',
      'Тимофей',
      'Тимур',
      'Фёдор',
      'Филипп',
      'Эдгар',
      'Эдуард',
      'Эрик',
      'Юрий',
      'Ян',
      'Ярослав',
    ]
  };


  static const Map<String, List<String>> namesFemale = {
    'en': [
      'Alexandra',
      'Allison',
      'Amia',
      'Angelina',
      'Anna',
      'Ariana',
      'Ashley',
      'Brianna',
      'Caroline',
      'Chloe',
      'Claire',
      'Elizabeth',
      'Ella',
      'Emilia',
      'Emily',
      'Emma',
      'Evelyn',
      'Faith',
      'Gabrielle',
      'Grace',
      'Hailey',
      'Haley',
      'Hannah',
      'Isabella',
      'Jasmine',
      'Jenna',
      'Jennifer',
      'Jessica',
      'Jocelyn',
      'Julia',
      'Kaitlyn',
      'Katelyn',
      'Katherine',
      'Kayla',
      'Kimberly',
      'Leah',
      'Lillian',
      'Lily',
      'Madeline',
      'Madison',
      'Maria',
      'Mary',
      'Maya',
      'Megan',
      'Mia',
      'Michelle',
      'Molly',
      'Morgan',
      'Natalie',
      'Olivia',
      'Paige',
      'Rachel',
      'Rebecca',
      'Riley',
      'Samantha',
      'Sarah',
      'Sophia',
      'Stephanie',
      'Taylor',
      'Vanessa',
      'Victoria',
      'Zoe',
    ],
    'ru': [
      'Александра',
      'Алёна',
      'Алина',
      'Алиса',
      'Алла',
      'Альбина',
      'Амина',
      'Анастасия',
      'Ангелина',
      'Анжела',
      'Анна',
      'Антонина',
      'Арина',
      'Валентина',
      'Валерия',
      'Варвара',
      'Василиса',
      'Вера',
      'Вероника',
      'Виктория',
      'Виолетта',
      'Виталина',
      'Галина',
      'Дарья',
      'Диана',
      'Дина',
      'Ева',
      'Евгения',
      'Екатерина',
      'Елена',
      'Елизавета',
      'Жанна',
      'Злата',
      'Зоя',
      'Илона',
      'Инна',
      'Ирина',
      'Карина',
      'Каролина',
      'Кира',
      'Кристина',
      'Ксения',
      'Лариса',
      'Лидия',
      'Лилия',
      'Любовь',
      'Людмила',
      'Майя',
      'Маргарита',
      'Марианна',
      'Марина',
      'Мария',
      'Надежда',
      'Наталия',
      'Нина',
      'Оксана',
      'Олеся',
      'Ольга',
      'Полина',
      'Раиса',
      'Рината',
      'Руслана',
      'Светлана',
      'Снежана',
      'София',
      'Таисия',
      'Тамара',
      'Татьяна',
      'Ульяна',
      'Юлия',
      'Яна',
    ]
  };




  static const Map<String, List<String>> namesMaleCodes = {
    'en': [
      'Iron Man',
      'Adam (naked)',
      'Ad board',
      'Aid (doctor)',
      'Alex from Madagascar',
      'Alexander Makedonski, in armor with a shield',
      'Enderman',
      'Ant',
      'Ant + neon',
      'Astronomer with telescope',
      'Ostrich',
      'Bang',
      'Blind',
      'Brandon Stark, in a wheelchair / Bra',
      'Flashlight',
      'Bright (like 6ixnin9)',
      'Calendar',
      'Photographer',
      'Fat (many calories)',
      'Cart',
      'Charmer',
      'Chair',
      'Christian',
      'Christopher Columbus',
      'Cod',
      'Cole',
      'Cola',
      'Conor mcgregor fighter',
      'Deny - let him be a Goth',
      'Like Davy Jones',
      'Devil',
      'die go - walking dead',
      'Dominic Toretto',
      'Dill',
      'Elephant',
      'Erection',
      'Like a titan Thanos',
      'Avenger (any of them)',
      'Gabon viper snake',
      'Government (In a suit)',
      'Hairy',
      'Hunter',
      'Eagle',
      'Icy zek',
      'Icy',
      'Jack Sparrow',
      'Michael Jackson',
      'Jacuzzi - in only swimming trunks',
      'Jedi',
      'Jam',
      'Jason chainsaw',
      'Gay + dandelion',
      'Mouse Jerry',
      'Jesse pinkman (the image of a drug addict)',
      'Jesus',
      'Jokes - like a clown',
      'Jon Snow',
      'Yogi',
      'Horse',
      'Rose',
      'Joker',
      'Huawei phone',
      'Yula',
      'Juice (Ghast (minecraft))',
      'Caviar',
      'Killed',
      'Big Ban',
      'Loggy',
      'Luckiest (with roulette)',
      'Lunatic',
      'Luke Skywalker',
      'Mason',
      'Like a mutton - with horns',
      'With a microphone - sings',
      'Midget',
      'Nut',
      'Nut',
      'Nike sneakers',
      'Supernova',
      'Oven',
      'Like a star (from Spongebob SquarePants)',
      'Very rich',
      'Robot',
      'Dressed in a rye bread suit',
      'Sumo wrestler',
      'Shorn (bald)',
      'Bus',
      'Stealer (with gloves, glasses)',
      'Tomato',
      'time - clock',
      'Tiled',
      'Like Will from Pirates of the Caribbean',
      'Smeared with white paint',
      'Caviar',
      'Zucchini',
    ],
    'ru': [
      'Сантехник',
      'Лекарь (Лёха)',
      'Альберт Эйнштейн - показывает язык, пишет формулы',
      '(Толик) - столик - встаёт за стол, дерётся столом',
      'Муравей (ant)',
      'Антенна - обвешан антенами',
      'Аккордеон - играет на нём',
      'Со стогом сена',
      'Художник - рисует картины (арт)',
      'Король Артур',
      'С прической АФРО',
      'С огромной бородой',
      'обливает себя ведром воды',
      'Купедон',
      'Кавалерист',
      'Лис',
      'Победитель, с кубком',
      'Есть витамины',
      'Мир (глобус)',
      'Властелин колец - образ хоббита',
      'Всем владеет, сидит на троне',
      '(Слава) - в одних сланцах и трусах',
      '(Гена) Крокодил',
      'Географ, с картой',
      'Хлеб',
      '(Горе) Плачет, с носовым платком',
      'Тхеквондист/каратист (Дан)',
      'Редиска',
      '(Метр) Линейка',
      '(Гений) - образ ботаника',
      '(Гора) - мускулистый',
      '(Сахар) Толстый сладкоешка, ест сладости ',
      'Ива',
      'Иголка',
      'Ил',
      'Патриарх Кирилл',
      'Кость',
      'Лев',
      'Черепашка-ниндзя',
      'Макароны',
      'Макдональс ловер',
      'Копьютер (Марк I)',
      '(Матрица) - как Нео, весь в чёрном, в очках',
      'Медведь',
      'Кит',
      'Кол',
      'Лежит на лежанке',
      'Оса',
      'Павлин',
      'Петух',
      'Тянет репу',
      'Ромашка',
      'Росток',
      'Слон',
      'Русал',
      'Поп (святой)',
      'Гопник с семечками',
      'Серьги',
      'Станок',
      'Трава (степь)',
      'Тарантул',
      'Фея',
      'Кот (Мур)',
      'Ведро',
      'Артист, яркий',
      'Курит табак (от него пахнет перегаром)',
      'Дикообраз (Эдик)',
      'Образ Крика с маской',
      'Космонавт (Гагарин)',
      'Енот',
      'Яростный',
    ]
  };




  static const Map<String, List<String>> namesFemaleCodes = {
    'en': [
      'Alexander Makedonsky',
      'Alien',
      'army (militarry)',
      'Angel',
      'Ant',
      'Rie bread',
      'Ashes',
      'Brilliant',
      'Crown',
      'Clown',
      'Vaccum cleaner',
      'Elizabeth from pirates of the caribbean',
      'Elephant',
      'Dragon (Emilia Clarke)',
      'Emo',
      'Emma form film',
      'Evil',
      'Prays',
      'Gabon viper snake',
      'Greek',
      'Hail (a big lump)',
      'Healthy (sporting)',
      'Hannah Montana',
      'Bell',
      'Mine (land)',
      'Gangster',
      'General',
      'Jessus',
      'Juice',
      'Yula',
      'Cat',
      'Cat',
      'Cat',
      'Bicycle',
      'Cyborg',
      'Leaf',
      'Lily',
      'Lily',
      'Model',
      'Mad',
      'Market (saleswoman)',
      'Bloody Mary',
      'Pigeon (from May month view)',
      'minigun (mega)',
      'Microphone',
      'Mesh',
      'Mole',
      'Morgen (German) - in pajamas',
      'Natalie from Avengers',
      'Olive',
      'Page (Hung with pages from the book)',
      'X-ray',
      'Ribbon',
      'Racer',
      'Sumo wrestler',
      'Sardine',
      'Sofa',
      'Stem + fan',
      'Tail',
      'Van',
      'Victory (with a cup)',
      'Zone',
    ],
    'ru': [
      'Образ сантехника',
      'Шоколадка',
      'Олень',
      'Лиса',
      'Разговаривает по телефону',
      'Альбинос',
      'Молится (аминь)',
      'Ананас',
      'Ангел',
      'Ангел + желе',
      'Манная каша',
      'Антенна',
      'Ариэль (русалка)',
      'Образ купидона',
      'Кавалеристка',
      'Варит, с варежками, в фартуке',
      'Зеркало (прекрасная)',
      'Монашка (верит)',
      'Веревка',
      'С кубком (победа)',
      'В фиолетовом платье (violet)',
      'Есть витамины',
      'Коп (мигалки)',
      'С подарками и тортом',
      'Каратистка (дан)',
      'Динозавр',
      'Ева',
      'Заучка, в очках (гений)',
      'Катер',
      'В листьях клёна',
      'Лижит чупа-чупс',
      'Образ жены-невесты',
      'Золотая',
      'Зомби',
      'Космонавтка',
      'Инопланетянка',
      'Ириска',
      'Карась',
      'Королева',
      'Образ шахтёра (с киркой)',
      'Крест',
      'Печатает (ксерокс)',
      'Продавщица (ларёк)',
      'Мидия',
      'Лилия',
      'С сердцем',
      'Как Людовик (с длинными, кудрявыми волосами)',
      'Голубь (образ месяца)',
      'Маргарин',
      'Тонет (марианская впадина)',
      'Огурец (маринованный)',
      'Статуя (Дева Мария)',
      'Выбирает одежду',
      'Истребитель (Нато)',
      'Ниндзя',
      'Бык (Ox)',
      'Обмотана леской',
      'Масло подсолненое (oil)',
      'Полено',
      'Бог Ра',
      'Тянет репу',
      'Слониха',
      'Лампочка',
      'Снегурочка',
      'Образ статуи в столице Болгарии',
      'Боксерша (Тайский бокс)',
      'С огромными томами (толстыми книжками)',
      'В татуировках',
      'Улий',
      'Юла',
      'Енотиха',
    ]
  };
}